languageCode = 'en-us'
title = 'WaterLily'

[menus]
[[menus.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 10
  params = { icon = "categories" }
[[menus.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20
  params = { icon = "tags" }
[[menus.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  params = { icon = "archives" }
  weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
